proxy:
  secretToken: "a2fb488cd373855647d120e9f77567a431a61aa39c1a38631bc5d7ec10308179"
  https:
    type: letsencrypt
    hosts:
      - "pasulkalab.calpolydatascience.org"
    letsencrypt:
      contactEmail: "ellisonbg@gmail.com"

rbac:
  enabled: false

hub:
  extraConfig: |
    from z2jh import get_config
    def is_admin(spawner):
      admins = get_config('auth.admin.users', [])
      if spawner.user.name in admins:
        return 'yes'
      else:
        return 'no'
    c.KubeSpawner.environment.update({
      "GRANT_SUDO": is_admin,
      "CHOWN_HOME": 'yes'
    })

auth:
  type: github
  whitelist:
    users:
      - llodolo
      - ellisonbg
  github:
    clientId: "7e09923449cad523f133"
    clientSecret: "7a4e0847ed6168aaaf2da58716e31cbdeccc8473"
    callbackUrl: "https://aaef0c3ff2ee111e8b0760200417670b-603777686.us-west-2.elb.amazonaws.com/hub/oauth_callback"
  admin:
    users:
      - apasulka
      - townsenddw

singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "test -f /home/jovyan/pasulkalab || ln -s /pasulkalab /home/jovyan/pasulkalab"]
  uid: 0
  storage:
    dynamic:
      storageClass: aws-efs
    homeMountPath: '/home/jovyan'
    extraVolumeMounts:
      - name: pv-group-pasulkalab
        mountPath: /pasulkalab
    extraVolumes:
      - name: pv-group-pasulkalab
        nfs:
          server: fs-ade87e04.efs.us-west-2.amazonaws.com 
          path: /
  image:
    name: calpolydatascience/rstudio-notebook
    tag: 0.1
  cmd: start-singleuser.sh

