proxy:
  secretToken: "c58389b3f80f67e84b1fff7b49252f3ade9e7e83777969609de2145cd0522244"
  https:
    type: letsencrypt
    hosts:
      - "data301-spring.calpolydatascience.org"
      - "data301b.calpolydatascience.org"
    letsencrypt:
      contactEmail: "ellisonbg@gmail.com"

rbac:
  enabled: false

hub:
  extraConfig: |
    from z2jh import get_config
    def is_admin(spawner):
      admins = get_config('auth.admin.users', [])
      if spawner.user.name in admins:
        return 'yes'
      else:
        return 'no'
    c.KubeSpawner.environment.update({
      "GRANT_SUDO": is_admin,
      "CHOWN_HOME": 'yes'
    })

auth:
  type: github
  whitelist:
    users:
      - data301
  admin:
    users:
      - dlsun
      - townsenddw
      - data301
      - ellisonbg
  github:
    clientId: "3c6f0494721213782ae1"
    clientSecret: "ad15a334e20a135b05e3956bd6f01c039bd81734"
    callbackUrl: "https://data301-spring.calpolydatascience.org/hub/oauth_callback"

singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "test -L /home/jovyan/data301 || ln -s /data301 /home/jovyan/data301"]
  uid: 0
  fsGid: 1000
  storage:
    dynamic:
      storageClass: aws-efs
    homeMountPath: '/home/jovyan'
    extraVolumeMounts:
      - name: pv-class-data301
        mountPath: /data301
    extraVolumes:
      - name: pv-class-data301
        nfs:
          server: fs-c3e97f6a.efs.us-west-2.amazonaws.com 
          path: /
  image:
    name: calpolydatascience/data301-notebook
    tag: 0.1
  cpu:
    limit:
    guarantee:
  memory:
    limit: 2G
    guarantee: 512Mi
  cmd: start-singleuser.sh
  defaultUrl: /lab

