proxy:
  secretToken: "9b515618fa1b9838883b6f54aae2b5ce7ca3960503ea8e0e00c1e2c88001d1ea"
  https:
    type: letsencrypt
    hosts:
      - "stat331.calpolydatascience.org"
    letsencrypt:
      contactEmail: "ellisonbg@gmail.com"

rbac:
  enabled: false

hub:
  extraConfig: |
    from z2jh import get_config
    def is_admin(spawner):
      admins = get_config('auth.admin.users', [])
      if spawner.user.name in admins:
        return 'yes'
      else:
        return 'no'
    c.KubeSpawner.environment.update({
      "GRANT_SUDO": is_admin,
      "CHOWN_HOME": 'yes'
    })

auth:
  type: github
  whitelist:
    users:
      - ellisonbg
  admin:
    users:
      - hglanz
      - ellisonbg
      - townsenddw
  github:
    clientId: "636c22f89688a209abdf"
    clientSecret: "2111ddf37339444f860fd831d362c8b097457449"
    callbackUrl: "https://stat331.calpolydatascience.org/hub/oauth_callback"

singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "test -L /home/jovyan/stat331 || ln -s /stat331 /home/jovyan/stat331"]
  uid: 0
  storage:
    dynamic:
      storageClass: aws-efs
    homeMountPath: '/home/jovyan'
    extraVolumeMounts:
      - name: pv-class-stat331
        mountPath: /stat331
    extraVolumes:
      - name: pv-class-stat331
        nfs:
          server: fs-fee97f57.efs.us-west-2.amazonaws.com 
          path: /
  image:
    name: calpolydatascience/rstudio-notebook
    tag: 0.1
  cpu:
    limit:
    guarantee:
  memory:
    limit: 1G
    guarantee: 512M
  cmd: start-singleuser.sh

prePuller:
  continuous:
    enabled: true

