proxy:
  secretToken: "445c50e1df9bf2fcdb9f88ef56e88e6526e5af131ff5d7df3fa8a14b1a756d3a"

rbac:
  enabled: false

hub:
  uid: 0
  extraVolumeMounts:
    - name: pv-home
      mountPath: /persistentvolumes
  extraVolumes:
    - name: pv-home
      nfs:
        server: fs-8e79f327.efs.us-west-2.amazonaws.com 
        path: /
  extraConfig: |
    c.KubeSpawner.environment.update({"GRANT_SUDO": '1'})
  # image:
  #   name: calpolydatascience/k8s-hub
  #   tag: jhd67ff

auth:
  admin:
    users:
      - admin

singleuser:
  # uid: 0
  # extraEnv:
  #   GRANT_SUDO: 1
    #PATH: $PATH:/srv/venv/bin
  fsGid: 100
  storage:
    dynamic:
      storageClass: aws-efs
    homeMountPath: '/home/jovyan'
    extraVolumeMounts:
      - name: pv-class-stat301
        mountPath: /data
    extraVolumes:
      - name: pv-class-stat301
        nfs:
          server: fs-4a0396e3.efs.us-west-2.amazonaws.com 
          path: /pasulkalab
  image:
    name: calpolydatascience/rstudio
    tag: 0.2
  cmd: jupyterhub-singleuser


