proxy:
  secretToken: "445c50e1df9bf2fcdb9f88ef56e88e6526e5af131ff5d7df3fa8a14b1a756d3a"

rbac:
  enabled: false

hub:
  uid: 0
  extraVolumeMounts:
    - name: pv-home
      mountPath: /persistentvolumes
  extraVolumes:
    - name: pv-home
      nfs:
        server: fs-8e79f327.efs.us-west-2.amazonaws.com 
        path: /
  # image:
  #   name: calpolydatascience/k8s-hub
  #   tag: jhd67ff

singleuser:
  storage:
    dynamic:
      storageClass: aws-efs
    homeMountPath: '/home/jovyan'
    extraVolumeMounts:
      - name: pv-group-pasulkalab
        mountPath: /data
    extraVolumes:
      - name: pv-group-pasulkalab
        nfs:
          server: fs-4a0396e3.efs.us-west-2.amazonaws.com 
          path: /pasulkalab
  image:
    name: jupyter/scipy-notebook
    tag: c7fb6660d096
  cmd: start-singleuser.sh

