proxy:
  secretToken: "445c50e1df9bf2fcdb9f88ef56e88e6526e5af131ff5d7df3fa8a14b1a756d3a"

rbac:
  enabled: false

hub:
  uid: 0
  extraVolumeMounts:
    - name: pv-home
      mountPath: /persistentvolumes
  extraVolumes:
    - name: pv-home
      nfs:
        server: fs-8e79f327.efs.us-west-2.amazonaws.com 
        path: /
  extraConfig: |
    from z2jh import get_config
    def is_admin(spawner):
      admins = get_config('auth.admin.users', [])
      if spawner.user.name in admins:
        return 'yes'
      else:
        return 'no'
    c.KubeSpawner.environment.update({
      "GRANT_SUDO": is_admin,
      "CHOWN_HOME": 'yes'
    })
  # image:
  #   name: calpolydatascience/k8s-hub
  #   tag: jhd67ff

auth:
  admin:
    users:
      - admin
      - dlsun
      - townsenddw

singleuser:
  # extraEnv:
  #   CHOWN_HOME: '1'
  uid: 0
  fsGid: 1000
  storage:
    dynamic:
      storageClass: aws-efs
    homeMountPath: '/home/jovyan'
    extraVolumeMounts:
      - name: pv-class-data301
        mountPath: /data
    extraVolumes:
      - name: pv-class-data301
        nfs:
          server: fs-4a0396e3.efs.us-west-2.amazonaws.com 
          path: /
  image:
    name: jupyter/base-notebook
    tag: 29b68cd9e187
  cmd: start-singleuser.sh

